"""empty message

Revision ID: 444acfcfde78
Revises: 1f4910056ae8
Create Date: 2020-09-22 18:02:13.295117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444acfcfde78'
down_revision = '1f4910056ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
